[package]
name = "hex_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { git = "https://github.com/a-underscore/hex", version = "0.1.0" }
hex_instance = { git = "https://github.com/a-underscore/hex_instance", version = "0.1.0" }
